### PR TITLE
CLI Windows Support

### PR DESCRIPTION
**Pull request by PraveenGandhi**
Hi Felipe,

**Few Points to consider:**

1. Windows New application task issue: Posix Permissions (fixed)
2. New kales.bat file added (actually not required IMHO, because of gradle application plugin generated distribution) ```gradle build``` or ```gradle distZip``` or ```gradle distTar```
3. Even for other Operating systems, gradle generated distributions (.zip/.tar inside build/distributions) are enough IMHO (see first image below)
4. I have used gradle generated distribution in my system (see the second image)
5. ```gradle run``` on newly created app fails (may be due to missing route handler for URL http://0.0.0.0:8080/)
6. kales-cli tests are failing in windows (yet to be fixed)

Share your thoughts on this to take it further.

image

image

> gradle run (failed may be due to missing route handler for URL http://0.0.0.0:8080/)

image

### CODE REVIEW

**Comment by felipecsl** [comment]
@PraveenGandhi if I understand you correctly, are you saying we could just use the distribution package generated by gradle and that should be enough to run kales on most OSes?

**Comment by PraveenGandhi** [comment]
Yes, that's right. In fact, I have used it. One which is downloaded using cURL is zip with two files (shell script and the jar around 40Mb size). Similarly, gradle generated distribution has bin (executable scripts) lib (libraries including kales-cli jar).

**Comment by felipecsl** [comment]
That's awesome, I didn't know about that.
I guess this means we don't need to keep this `bat` script at all since it will be autogenerated by gradle, right? If that's the case I'll just close this PR. Thanks a lot for your contribution anyways!

**Comment by PraveenGandhi** [comment]
Thank you. One commit might be useful https://github.com/felipecsl/kales/pull/63/commits/b4cea9b994b5964c39fc8fb89c4cf493767cdecf

**Comment by felipecsl** [comment]
I'll merge this "as is" and then refactor to use the Gradle-generated distribution scripts, thanks for your contribution @PraveenGandhi

**Pull request merged**
