### PR TITLE
Add kales-cli db migrate task

### PR DESCRIPTION
**Pull request by felipecsl**
Thanks to the awesome Kotlin database migrations implementation by @KenjiOhtsuka on https://github.com/KenjiOhtsuka/harmonica we don't have to reinvent the wheel and reuse it on Kales.

@KenjiOhtsuka I couldn't find a separate maven library with just the harmonica core otherwise I'd have used it here. I hope you're fine with me copy-pasting that code here on Kales where it will be part of a bigger Kotlin web framework similar to Rails. The GPL v3 license you're using seems to allow that but let me know if you'd like me to attribute the code to you anywhere and I'd be more than happy to do that!

In the future I plan to adapt it for Kales' needs but for now It's 99% copy-paste. Let me know what you think!

### CODE REVIEW

**Comment by KenjiOhtsuka** [comment]
@felipecsl 
Hello, you need only core part, right?
I will separate "core" to another jar. After that, you can use the functions by only adding the dependency.

**Comment by KenjiOhtsuka** [comment]
@felipecsl 
I have a question. How do you want to use Harmonica core?

Would you write some example codes?
I wondered how you use the classes internally.

**Comment by felipecsl** [comment]
Thank you for your quick reply @KenjiOhtsuka 
I haven't figured out that part yet, I'll have to look into how it's currently used by the Gradle Plugin you built and then adapt it to my needs.
To summarize on a high level, there is a command line java application that will invoke the migration, eg.: `kales db:migrate` to run the migrations and `kales generate migration foo` to generate a new migration. Basically the same interface that you can find with Rails. Does that make sense?
I'm not sure whether or not harmonica will need changes to its API in order to accommodate that, but I'd be happy to contribute if you're open to that.
Once you have the core jar up, please let me know and I can replace it here. How does that sound?

**Comment by KenjiOhtsuka** [comment]
@felipecsl 
So, you want migration feature, right?
For that purpose, the following commands create, execute, rollback migrations.

* `./gradlew jarmonicaCreate` => create migrtion
* `./gradlew jarmonicaUp` => execute migration
* `./gradlew jarmonicaDown` => rollback one migration

Those commands run the main functions in task directory. https://github.com/KenjiOhtsuka/harmonica/tree/develop/src/main/kotlin/com/improve_future/harmonica/task

https://improve-future.com/en/spring-boot-with-db-migration.html
https://github.com/KenjiOhtsuka/harmonica/wiki/Jarmonica-Usage

**Comment by felipecsl** [comment]
Yup, I saw those but I don't want to run them as part of a Gradle task, it needs to be a standalone tool, that's why it might need some customization

**Comment by KenjiOhtsuka** [comment]
@felipecsl 
For that purpose, what you have to do is only add Harmonca into the dependencies and create your class which inherits `JarmonicaTaskMain`, and add some code like `JarmonicaUpMain`, in my understanding. 🤔

**Comment by felipecsl** [comment]
hmm interesting, I didn't see those, sounds like that *could* work, however I still think it would be valuable to have a separate jar for harmonica core because I don't want to bring all these transitive dependencies, I assume a lot of them won't be needed for my use case: https://github.com/KenjiOhtsuka/harmonica/blob/develop/build.gradle#L79-L105

**Comment by KenjiOhtsuka** [comment]
Yes, I want to, but it takes some time.

**Comment by felipecsl** [comment]
👍 no rush, thanks!

**Comment by felipecsl** [comment]
@KenjiOhtsuka I was able to get it working in case you're curious!

**Pull request merged**
